version: '3.4'

services:
  microserviceprototype:
    container_name: microserviceprototype
    restart: always
    build:
      context: ./
      dockerfile: "Dockerfile"
  consumer:
    container_name: consumer
    restart: always
    build:
      context: ./Consumer
      dockerfile: "Dockerfile"
