# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: s6appsecretproviderclass
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                    # Set to true for using managed identity
    userAssignedIdentityID: ff06d033-9ff6-47c5-961a-04d7ddf377c1    # Set the clientID of the user-assigned managed identity to use
    keyvaultName: s6appVault                                        # Set to the name of your key vault
    cloudName: ""                                                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: AccountDBConnectionString
          objectType: secret              
          objectVersion: ""               
    tenantId: c66b6765-b794-4a2b-84ed-845b341c086a                  # The tenant ID of the key vault
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: s6appsecretproviderclass
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"    
#     userAssignedIdentityID: ""      
#     keyvaultName: s6appVault
#     cloudName: "AzurePublicCloud"                  
#     objects:  |
#       array:
#         - |
#           objectName: AccountDBConnectionString
#           objectType: secret        
#           objectVersion: ""         
#     tenantId: c66b6765-b794-4a2b-84ed-845b341c086a          