version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  newtask:
    container_name: newtask
    restart: always
    build:
      context: "./NewTask"
      dockerfile: "Dockerfile"
    ports:
      - "8092:80"
  worker1:
    container_name: worker1
    restart: always
    build:
      context: "./Worker"
      dockerfile: "Dockerfile"
    ports:
      - "8093:80"
  worker2:
    container_name: worker2
    restart: always
    build:
      context: "./Worker"
      dockerfile: "Dockerfile"
    ports:
      - "8094:80"
