version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    container_name: producer
    restart: always
    build:
      context: "./Producer"
      dockerfile: "Dockerfile"
    ports:
      - "8091:80"
  consumer:
    container_name: consumer
    restart: always
    build:
      context: "./Consumer"
      dockerfile: "Dockerfile"
    ports:
      - "8090:80"
