version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8099:8080"
  accountservice_db:
    container_name: accountservice_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: account
    ports:
      - "8100:5432"
  authservice_db:
    container_name: authservice_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: auth
    ports:
      - "8102:5432"
  chatservice_db:
    container_name: chatservice_db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: chat
    ports:
      - "8103:5432"
  accountservice:
    container_name: accountservice
    restart: always
    build:
      context: "./AccountService"
      dockerfile: "Dockerfile"
    ports:
      - "8095:80"
  authservice:
    container_name: authservice
    restart: always
    build:
      context: "./AuthService"
      dockerfile: "Dockerfile"
    ports:
      - "8096:80"
  chatservice:
    container_name: chatservice
    restart: always
    build:
      context: "./ChatService"
      dockerfile: "Dockerfile"
    ports:
      - "8097:80"
  moderationservice:
    container_name: moderationservice
    restart: always
    build:
      context: "./ModerationService"
      dockerfile: "Dockerfile"
    ports:
      - "8098:80"
  apigateway:
    container_name: apigateway
    restart: always
    build:
      context: "./APIGateway"
      dockerfile: "Dockerfile"
    ports:
      - "8101:80"