version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  accountservice:
    container_name: accountservice
    restart: always
    build:
      context: "./AccountService"
      dockerfile: "Dockerfile"
    ports:
      - "8095:80"
  authservice:
    container_name: authservice
    restart: always
    build:
      context: "./AuthService"
      dockerfile: "Dockerfile"
    ports:
      - "8096:80"
  chatservice:
    container_name: chatservice
    restart: always
    build:
      context: "./ChatService"
      dockerfile: "Dockerfile"
    ports:
      - "8097:80"
  moderationservice:
    container_name: moderationservice
    restart: always
    build:
      context: "./ModerationService"
      dockerfile: "Dockerfile"
    ports:
      - "8098:80"