name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "RabbitMQPrototype/AccountService/**"
      - "RabbitMQPrototype/APIGateway/**"
      - "RabbitMQPrototype/AuthService/**"
      - "RabbitMQPrototype/ChatService/**"

jobs:

  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo 
      uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          AccountService:
            - 'RabbitMQPrototype/AccountService/**'
          APIGateway:
            - 'RabbitMQPrototype/APIGateway/**'
          AuthService:
            - 'RabbitMQPrototype/AuthService/**'
          ChatService:
            - 'RabbitMQPrototype/ChatService/**'
          
        
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: wesje101/s6-2_personal_project
        
    - name: Build and publish Account Service Docker image
      if: steps.filter.outputs.AccountService == 'true'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./RabbitMQPrototype/AccountService
        push: true
        tags: wesje101/s6-2_personal_project:accountservice
        labels: ${{ steps.meta.output.labels }}
        
    - name: Build and publish Auth Service Docker image
      if: steps.filter.outputs.AuthService == 'true'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./RabbitMQPrototype/AuthService
        push: true
        tags: wesje101/s6-2_personal_project:authservice
        labels: ${{ steps.meta.output.labels }}

    - name: Build and publish API Gateway Docker image
      if: steps.filter.outputs.APIGateway == 'true'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./RabbitMQPrototype/APIGateway
        push: true
        tags: wesje101/s6-2_personal_project:apigateway
        labels: ${{ steps.meta.output.labels }}
        
    - name: Build and publish Chat service Docker image
      if: steps.filter.outputs.ChatService == 'true'
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./RabbitMQPrototype/ChatService
        push: true
        tags: wesje101/s6-2_personal_project:chatservice
        labels: ${{ steps.meta.output.labels }}
